### ISSUE TITLE
Joke appears to break guidelines

### ISSUE THREAD

**Issue by AshlinHarris** [cityjumper/Jokes.jl#11]
[This joke](https://github.com/cityjumper/Jokes.jl/blob/1d7253fd8b56c5d6c27bee4b22b937b93142cf5b/src/Jokes.jl#L20) appears to break the current guidelines.

**Comment by AshlinHarris** [comment]
https://github.com/cityjumper/Jokes.jl/pull/12

**Comment by cityjumper** [comment]
Indeed you are right, let me fix it.

**Comment by cityjumper** [comment]
Now merged in
